package.json

Leading to 404 from npm package name. I believe we need to publish a new version to update npm page.

fix(package): wrong link to GitHub repo

---

package.json

https://github.com/nuxt/framework/issues/2724, https://github.com/nuxt/framework/issues/5482
When something that has been aliased to `proxy-cjs` is accessed with a subpath, it falls back to the next valid subpath, which will never succeed: import (`unenv/runtime/*` => `unenv/runtime/mock/proxy-cjs/.cjs`).

fix: allow mocking subpaths of proxy

---

src/runtime/npm/node-fetch.ts

This adds a named fetch export for compatibility with `node-fetch-native`: https://github.com/unjs/node-fetch-native/blob/main/src/index.ts#L12.

fix: export named `fetch` from `node-fetch` polyfill

---

src/runtime/node/events/index.ts

This PR exports the `once` function in the `event`  node runtime polyfill
patched the library (using pnpm) in my current project, was able to complete the build successfully.
should fix #54

fix(events): export once function

---

src/runtime/npm/debug.ts

https://github.com/nuxt/nuxt/issues/15608
This adds the `extend` method to our debug mock.
https://github.com/debug-js/debug/blob/d1616622e4d404863c5a98443f755b4006e971dc/src/common.js#L149-L153

fix: add `extend` method to debug mock

---

src/runtime/node/stream/writable.ts

resolves [#https://github.com/unjs/nitro/issues/950](https://github.com/unjs/nitro/issues/950)
Support writing multiple chunks using `res.write`. 
**Note:** This is a less efficient method of concatenating buffers each time but is compatible with the current direct fetch implementation that expects a (merged) body. Later improving stream support

feat(node/stream): support writing multiple chunks

---

README.md
src/presets/nodeless.ts
src/runtime/node/crypto/index.ts

[unjs/uncrypto](https://github.com/unjs/uncrypto) has a dual export for node/web crypto but some libraries / export conditions won't pick it. It adds built-in crypto polywill via global natives to also avoid a mock with never-resolving promises.

feat(node): add `node:crypto` polyfill

---

src/runtime/node/crypto/index.ts

Added export of `randomBytes` to the crypto polyfill.  If another dependency requires it currently, nitro will fail to build. Currently webcrypto does not have a `randomBytes` method
```
[nitro 2:36:51 PM]  ERROR  RollupError: "randomBytes" is not exported by "node_modules/unenv/runtime/node/crypto/index.mjs", imported by "node_modules/@firebase/firestore/dist/lite/index.node.mjs".
5: import { FirebaseError, getDefaultEmulatorHostnameAndPort, createMockUserToken, getModularInstance, deepEqual } from ...
6: import nodeFetch from 'node-fetch';
7: import { randomBytes as randomBytes$1 } from 'crypto';
^
8:
9: const version$1 = "3.7.2";
ERROR  "randomBytes" is not exported by "node_modules/unenv/runtime/node/crypto/index.mjs", imported by …
```

feat(node/crypto): implement `randomBytes`

---

src/runtime/fetch/index.ts
src/runtime/node/http/_response.ts

fix https://github.com/unjs/unenv/issues/118
This PR changes the odd unenv behaviour that joined multiple value headers instead of preserving the array.
This brings `setHeader` behaviour in line with `appendHeader` when it comes to multiple values headers.

fix(node): preserve http number header type with `setHeader` 

---

src/runtime/node/crypto/node.ts
src/runtime/node/crypto/web.ts

The latest change broke some Nuxt deployments to Deno deploy for me. Deno's webcrypto is somewhat different, and `...globalThis.crypto` does not work in Deno. This replaces it with a custom getter that retrieves the correct value instead. This adds some overhead, but is required for Deno compatibility.

fix(node:crypto): properly call web crypto methods

---

src/runtime/_internal/utils.ts
src/runtime/mock/empty.ts
src/runtime/mock/noop.ts
src/runtime/mock/proxy.ts
src/runtime/node/async_hooks/_async-hook.ts
src/runtime/node/async_hooks/_async-local-storage.ts
src/runtime/node/async_hooks/_async-resource.ts
src/runtime/node/buffer/_file.ts
src/runtime/node/http/_request.ts
src/runtime/node/http/_response.ts
src/runtime/node/net/socket.ts
src/runtime/node/stream/readable.ts
src/runtime/node/stream/transform.ts
src/runtime/node/stream/writable.ts
src/runtime/node/util/_mime.ts

it is commonly required to identify if something is coming from unenv or not specially for classes and mocked objects. 
This PR adds `__unenv__` property to class (instances) and functions to identify.
**Note:** Since we were already using `req.__unenv__` for another purpose (https://github.com/unjs/unenv/issues/72), the type for `IncommingMessage` and `Readable` classes is unknown/object.

feat: expose `__unenv__` flag for unenv classes and functions

---

src/runtime/node/async_hooks/_async-hook.ts
src/runtime/node/async_hooks/_async-local-storage.ts
src/runtime/node/async_hooks/_async-resource.ts

allow overriding `AsyncHook`, `AsyncLocalStorage` and `AsyncResource` with `globalThis` and platform natives.

feat(node:async_hooks): allow overriding `AsyncHook`, `AsyncLocalStorage` and `AsyncResource` with `globalThis`

---

README.md
src/runtime/node/module/index.ts

resolves #147
Implement `node:module` namespace. All methods are polyfilled but it allows named exports and future implementation.

feat: polyfill `node:module`

---

src/runtime/npm/consola/utils.ts

resolves #143
Temporarily in unenv until consola support for edge lands (https://github.com/unjs/consola/issues/263)

feat: support `consola/utils` subpath

---

.gitignore
README.md
package.json
src/presets/deno.ts
src/presets/index.ts
test/deno.ts

This PR adds a new `deno` preset suitable to extend `nodeless` with supported modules. 
**Note:** For ⚠️ _partial_ supported modules, using this preset means disabling unenv support for them!
Support status for Node v20.10.0 vs Deno v1.38.5
Feature | Status | Details
--- | --- | ---
node:inspector/promises | ℹ️ unenv | Using unenv
node:readline/promises | ℹ️ unenv | Using unenv
node:stream/consumers | ✅ full | -
node:stream/promises | ✅ full | -
node:timers/promises | ⚠️ partial | Missing: `scheduler`
node:assert/strict | ⚠️ partial | Missing: `CallTracker`
node:dns/promises | ⚠️ partial | Missing: `lookupService`, `getDefaultResultOrder`
node:fs/promises | ⚠️ partial | Missing: `cp`, `statfs`, `lchmod`, `lchown`, `lutimes`, `constants`
node:path/posix | ⚠️ partial | Missing: `win32`, …

feat: experimental deno preset

---

.gitignore
README.md
package.json
pnpm-lock.yaml
src/presets/cloudflare.ts
src/presets/index.ts
test/_utils.ts
test/cloudflare.ts
test/deno.ts

resolves #97
Similar to https://github.com/unjs/unenv/pull/155 this adds a complimentary preset for nodeless that adds Cloudflare node compat support.
Status: (local `pnpm test:cf` node `v20.10.0` / wrangler `3.20.0`)
Feature | Status | Details
--- | --- | ---
node:inspector/promises | ℹ️ unenv | Using unenv
node:readline/promises | ℹ️ unenv | Using unenv
node:stream/consumers | ℹ️ unenv | Using unenv
node:stream/promises | ℹ️ unenv | Using unenv
node:timers/promises | ℹ️ unenv | Using unenv
node:assert/strict | ℹ️ unenv | Using unenv
node:dns/promises | ℹ️ unenv | Using unenv
node:fs/promises | ℹ️ unenv | Using unenv
node:path/posix | ℹ️ unenv | Using unenv
node:path/win32 | ℹ️ unenv | Using unenv
node:stream/web | ℹ️ unenv | Using unenv
node:util/types | ℹ️ unenv | Using unenv …

feat: experimental cloudflare preset

---

README.md
package.json
pnpm-lock.yaml
src/presets/index.ts
src/presets/vercel.ts
test/deno.ts
test/vercel.ts

Add support for vercel-edge node.js compatibility support (similar to #155, #156)
comparing https://unenv.vercel.dev against node 20.10.0 (local `pnpm test:vc`)
Feature | Status | Details
--- | --- | ---
node:inspector/promises | ℹ️ unenv | Using unenv
node:readline/promises | ℹ️ unenv | Using unenv
node:stream/consumers | ℹ️ unenv | Using unenv
node:stream/promises | ℹ️ unenv | Using unenv
node:timers/promises | ℹ️ unenv | Using unenv
node:assert/strict | ℹ️ unenv | Using unenv
node:dns/promises | ℹ️ unenv | Using unenv
node:fs/promises | ℹ️ unenv | Using unenv
node:path/posix | ℹ️ unenv | Using unenv
node:path/win32 | ℹ️ unenv | Using unenv
node:stream/web | ℹ️ unenv | Using unenv
node:util/types | ℹ️ unenv | Using unenv
node:_stream_passthrough | ℹ️ unenv | Using unenv …

feat: experimental vercel preset

---

src/runtime/node/stream/web/index.ts

n/a
Added the missing https://nodejs.org/api/webstreams.html#class-decompressionstream API to node:stream/web

fix(node:stream/web): add missing `DecompressionStream`

---

src/runtime/node/process/_process.ts

Idea from #183 use [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask) for [approximate `process.nextTick()`](https://nodejs.org/api/process.html#when-to-use-queuemicrotask-vs-processnexttick) in Node.js when available.

feat(node:process): prefer `queueMicrotask` for `process.nextTick` polyfill

---

src/presets/cloudflare.ts
src/runtime/polyfill/cloudflare.ts

Adds a polyfill for `process` to the Cloudflare preset which combines the [node polyfill](https://github.com/unjs/unenv/blob/main/src/runtime/node/process/_process.ts) with the [workerd polyfill](https://github.com/cloudflare/workerd/blob/main/src/node/internal/process.ts) implementation. We'd specifically like to retain the polyfilled `nextTick` from workerd which uses `queueMicrotask`, but benefit from all the other global `process` polyfills provided by unenv.

fix(cloudflare): make sure not fallback to `globalThis` for env

---

src/presets/nodeless.ts
src/runtime/_internal/utils.ts
src/runtime/node/dns/constants.ts
src/runtime/node/dns/index.ts
src/runtime/node/dns/promises/index.ts
src/runtime/node/fs/_fs.ts

Replaces the current auto-mocking of 'dns' to support destructured ESM imports and allow for functional polyfill coverage in the future.
Adds a polyfill for the `node:dns` module.
Also moves the helpful `notImplementedAsync` helper to `utils` from `fs` so that it can be reused.

feat(node:dns): polyfill `node:dns` module

---

src/presets/nodeless.ts
src/runtime/node/cluster/index.ts
src/runtime/node/events/_events.ts

Replaces the current auto-mocking of 'cluster' to support destructured ESM imports and allow for functional polyfill coverage in the future.
Adds a polyfill for the `node:cluster` module.

feat(node:cluster): polyfill `node:cluster` module

---

src/presets/nodeless.ts

These simply needed to be added to the preset and aliased to the existing node `path` polyfill

feat(node:path): add `path/posix` and `path/win32` subpaths

---

src/presets/nodeless.ts
src/runtime/node/https/index.ts

Adds the https module to the nodeless preset. Also adds a mock fallback for `globalAgent`.
@pi0 was there any reason why this wasn't added already?

feat(nodeless): add the `node:https` module

---

src/presets/nodeless.ts
src/runtime/node/child_process/index.ts

Replaces the current auto-mocking of 'child_process' to support destructured ESM imports and allow for functional polyfill coverage in the future.
Adds a polyfill for `child_process` module and includes in `nodeless` preset.
@pi0 you think it's ok to mark these as `notImplemented`?

feat(node:child_process): polyfill `node:child_process` module

---

src/runtime/node/dns/constants.ts

This fixes the dns error codes used in the node dns polyfill to use the correct values per the node implementation. The current types for `@types/node` are incorrect, and I've filed a [PR to update them](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69673). In the meantime, we'll use the correct codes with a little less type safety.

fix(node:dns): hotfix types mismatch

---

src/presets/nodeless.ts
src/runtime/node/domain/_domain.ts
src/runtime/node/domain/index.ts

Replaces the current auto-mocking of 'domain' to support destructured ESM imports and allow for functional polyfill coverage in the future.
Polyfills the `node:domain` module.

feat: polyfill `node:domain` module

---

src/presets/nodeless.ts
src/runtime/node/dgram/index.ts
src/runtime/node/dgram/socket.ts

Replaces the current auto-mocking of 'dgram' to support destructured ESM imports and allow for functional polyfill coverage in the future.
Polyfills the `node:dgram` module.

feat: polyfill `node:dgram` module

---

package.json
pnpm-lock.yaml
src/presets/nodeless.ts
src/runtime/node/querystring/index.ts

Replaces the current auto-mocking of 'querystring' to support destructured ESM imports and allow for functional polyfill coverage in the future.
Uses `ufo` to add a functional polyfill for the `querystring` module.

feat: polyfill `node:querystring` module

---

src/runtime/web/performance/_entry.ts
src/runtime/web/performance/_observer.ts
src/runtime/web/performance/_performance.ts
src/runtime/web/performance/index.ts

This PR adds a partial (node subset) implementation of web performances API mainly useful for https://github.com/unjs/unenv/pull/209
All expoirts will first try to use `globalThis.*` native version before falling back to polyfills.

feat: basic web performances api implementation

---

src/runtime/web/performance/_entry.ts
src/runtime/web/performance/_observer.ts
src/runtime/web/performance/_performance.ts
src/runtime/web/performance/index.ts

Continuation to #213
Adding `_*` variant exports that are explicit polyfills to allow mixed usage. (important: constructor is also only possible via polyfill and not with natives)
The polyfilled `_Performance` class also now prefers `globalThis.performance.now` if available (and `timeOrigin` of instance is unchanged or 0 in worked) 
Credits to @IgorMinar for ideas in https://github.com/unjs/unenv/pull/209#issuecomment-2130393653 by

refactor(web/performance): separate polyfill and native exports

---

README.md
src/presets/nodeless.ts
src/runtime/node/v8/deserializer.ts
src/runtime/node/v8/index.ts
src/runtime/node/v8/profiler.ts
src/runtime/node/v8/serializer.ts

Replaces the current auto-mocking of `v8` to support destructured ESM imports and allow for functional polyfill coverage in the future.

feat(node:v8): polyfill `node:v8` module

---

README.md
src/presets/nodeless.ts
src/runtime/node/readline/index.ts
src/runtime/node/readline/interface.ts
src/runtime/node/readline/promises/index.ts
src/runtime/node/readline/promises/interface.ts
src/runtime/node/readline/promises/readline.ts

Replaces the current auto-mocking of 'readline' to support destructured ESM imports and allow for functional polyfill coverage in the future.

feat(node:readline): polyfill `node:readline` module

---

README.md
src/presets/nodeless.ts
src/runtime/node/trace_events/index.ts
src/runtime/node/trace_events/tracing.ts

Replaces the current auto-mocking of `trace_events` to support destructured ESM imports and allow for functional polyfill coverage in the future.

feat: polyfill `node:trace_events` module

---

README.md
src/runtime/node/dns/index.ts

Forgot to re-export `promises` when implementing `node:dns` module.

feat(node:dns): export promises api from dns module

---

src/env.ts
src/presets/cloudflare.ts
src/types.ts

Sometimes an environment might want to undo any kind of inject configuration provided by the previous preset, because this environment guaratees that an API is provided natively and doesn't need to be supported via injection.
An example is Cloudflare's workerd, which natively support Blob and global when the nodejs_compat flag is turned on.

feat: support `inject` with `false` values to  override injections

---

src/presets/cloudflare.ts
src/presets/nodeless.ts
src/runtime/node/_global.ts
src/runtime/node/global.ts
src/runtime/node/process.ts
src/runtime/node/process/$cloudflare.ts
src/runtime/node/process/index.ts
src/runtime/polyfill/process.ts

This PR makes several related changes to how polyfilling of globalThis.process works:
- the `inject` setting in nodeless and cloudflare presets points to side-effect-free implementation
- the `polyfill` setting in nodeless preset is side-effecty and doesn't have any exports
- I refactored the code to use globalThis directly rather than via globaThis.ts as globalThis is now widely supported and doesn't need to be polyfilled
- I introduced src/runtime/node/process.ts following the precedence of src/runtime/node/global.ts
- I improved type-safety of the files I touched

feat(node, cloudflare): cleanup `globalThis.process` + add hybrid cloudflare impl

---

src/runtime/polyfill/process.ts

Fixes #260 (considering wrangler dep bumps to the latest nightly version and we don't have hoisting issue)
This PR adds back default export for `polyfill/process.ts` entry, improving its compatibility.

fix: add default export for `polyfill/process`

---

README.md
eslint.config.mjs
src/runtime/node/cluster/index.ts
src/runtime/node/dgram/internal/socket.ts
src/runtime/node/domain/internal/domain.ts
src/runtime/node/events/index.ts
src/runtime/node/events/internal/events.ts
src/runtime/node/readline/internal/interface.ts
src/runtime/node/stream/internal/readable.ts
src/runtime/node/stream/internal/writable.ts
src/runtime/node/worker_threads/internal/message-port.ts
src/runtime/node/worker_threads/internal/worker.ts

This PR rewrites `node:events` module using upstream Node.js code with class and added type safety.
Previous implementation was another rewrite of older browserify in unenv but adding new functionalities became more troubling.

feat!: rewrite `node:events` with upstream node impl

---

.github/workflows/autofix.yml
.github/workflows/ci.yml
automd.config.mjs
package.json
test/node-coverage.mjs

jiti was making some false-positives since it allows mixed esm/cjs interops.
Using native mjs, needs additional build step each time but makes tests more reliable.

chore: run node coverage with native esm

---

src/runtime/_internal/utils.ts

All current usages of `createNotImplementedError` explicitly `throw` the result. We were throwing inside util!

chore: remove extra `throw` in `createNotImplementedError`

---

src/runtime/node/dgram/internal/socket.ts
src/runtime/node/domain/internal/domain.ts
src/runtime/node/http/internal/request.ts
src/runtime/node/http/internal/response.ts
src/runtime/node/tls/internal/server.ts
src/runtime/node/tls/internal/tls-socket.ts
src/runtime/node/tty/internal/read-stream.ts

I have checked recent changes for usage for node modules within polyfills.
With explicit import of `node:`, we can allow hybrid polyfills.
With explicit relative import, we can allow polyfills extending each other.
This PR unifies to use `node:` with exception of polyfill classes extending each other -- other than EventEmitter : (constructors like `Readable` are imported from `node:*`)
Relative dependencies summary:
```
fetch => node/http (virtual request)
node/http => node/stream (extends polyfills)
node/net => node/stream (extends polyfills)
node/tls => node/net (extends polyfills)
node/tty => node/net (extends polyfills)
```

refactor(node): import from `node:` for non extend usages

---

package.json
pnpm-lock.yaml
src/presets/node.ts
src/runtime/polyfill/fetch.node.ts

With node 16 being EOL, node.js does not need a polyfill anymore.

refactor!: remove `node-fetch-native` polyfill for node

---

src/runtime/node/console/index.ts

Just like any other access to globalThis.console, we must use safe navigation operator for `createTask`.

fix(node:console): optional access to `console.createTask`

---

README.md
src/presets/cloudflare.ts
src/runtime/node/module/$cloudflare.ts

Related `workerd` PR: https://github.com/cloudflare/workerd/pull/2636
This PR changes `module` to be an hybrid polyfill and use the workerd available method implementations.
Is there anything else to change/update?
Thanks!
/cc @pi0

feat(cloudflare): implement `node:module` as an hybrid polyfill

---

src/runtime/node/timers/index.ts
src/runtime/node/timers/internal/immediate.ts
src/runtime/node/timers/internal/set-immediate.ts

As discussed in https://github.com/unjs/unenv/pull/302 using a timeout is a more sensible behavior

feat(node:timer): implement `setImmediate` with `setTimeout`

---

src/presets/cloudflare.ts
src/runtime/node/timers/$cloudflare.ts
src/runtime/node/timers/index.ts
src/runtime/node/timers/internal/set-immediate.ts
src/runtime/node/timers/internal/set-interval.ts
src/runtime/node/timers/internal/set-timeout.ts

We are exploring using unenv for `setImmediate`.
The desired behavior is run the callback in a `setTimeout(0)` instead of right away.

feat(cloudflare): use unenv implementation of `setImmediate` for `node:timers`

---

src/runtime/node/crypto/$cloudflare.ts

Resolves https://github.com/unjs/unenv/issues/306

fix(cloudflare): bind `getRandomValues` and `randomUUID` to the crypto object

---

src/presets/cloudflare.ts

`node:zlib` support just landed to workers. it will be included with the release on 09/23. we can add this to unenv as well.

add `zlib` to cloudflare compat modules

---

src/runtime/node/crypto/$cloudflare.ts

It appears that this is the only function in the webcrypto exports list that
needs to be bound to its original object.
Note that it must be bound to the `webcrypto` object even though workerd also
exports it on the `crypto` namespace directly.

fix: ensure Cloudflare webcrypto.getRandomBytes is bound to the correct this object

---

src/runtime/node/crypto/$cloudflare.ts

Fixes https://github.com/cloudflare/workerd/issues/2720
Validated with https://github.com/cloudflare/workerd/pull/2739

feat(cloudflare): update crypto hybrid polyfill

---

test/workerd/config.capnp

`unenv` is used by wrangler only when the `workerd` flag `nodejs_compat_v2` is active.
And `nodejs_compat_v2` is implied by `nodejs_compat` after [2024-09-23](https://developers.cloudflare.com/workers/runtime-apis/nodejs/#get-started).
This PR bumps the `compatibilityDate` past 2024-09-23.
`2024-10-04` is the max `compatibilityDate` supported by the packaged `workerd` (=it's build date).

test: bump compatibilityDate past 2024-09-23

---

package.json
pnpm-lock.yaml

Updates wrangler and workerd. After this pull-request lands, we can add `sys` and `buffer` to the nodejs_compat list of Cloudflare. I'll open another pull-request once this lands:

chore: update wrangler and workerd

---

src/runtime/node/buffer/$cloudflare.ts
test/workerd/tests.mjs

Fixes tests for cloudflare buffer. Reverts only `atob` and `btoa` changes.
Ref: https://github.com/unjs/unenv/pull/324

fix(node/buffer): add coudflare exports for `atob` and `btoa` and add tests

---

.github/CODEOWNERS

This came out of https://github.com/unjs/unenv/pull/325 which we should be able to approve and merge without @pi0  but we can't right due to the OWNERS config not being up todate.

chore: add cloudflare team to workerd tests codeowners

---

package.json
pnpm-lock.yaml
src/runtime/node/process/$cloudflare.ts

process.exit and process.platform are implemented in 20241018. See https://github.com/cloudflare/workerd/releases/tag/v1.20241018.0
Wramgler is [already using 20241018](https://github.com/cloudflare/workers-sdk/blob/1de309ba2222d7a73cefacef8d3eb60e8afdf5b4/packages/wrangler/package.json#L89) so this PR is ready to be merged

feat(cloudflare): update the process hybrid polyfill

---

package.json
pnpm-lock.yaml
src/presets/cloudflare.ts

See https://github.com/cloudflare/workerd/releases/tag/v1.20241022.0
Do not merge this until workerd uses [v1.20241022.0](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/package.json#L89)

feat(cloudflare): use querystring and url from workerd

---

src/presets/cloudflare.ts

`assert/strict` and `sys` aliases are available on workerd. we don't need unenv to handle them.

feat(cloudflare): remove unnecessary aliases

---

package.json
pnpm-lock.yaml
src/presets/cloudflare.ts
test/workerd/tests.mjs

path/win32 and path/posix are fixed in workerd [1.20241106.0](https://github.com/cloudflare/workerd/releases/tag/v1.20241106.0#:~:text=Add%20named%20exports%20for%20node%3Apath/win32%20and%20node%3Apath/posix%20by%20%40jasnell) which is integrated in wrangler 3.86
/cc @jasnell @anonrig

feat(cloudflare): use native path/posix and path/win32

---

src/runtime/node/module/index.ts

The implementation returns undefined - meaning no source map found. Note that the Node typings are wrong. However it is part of the possible returned values, see https://github.com/nodejs/node/pull/44397/files. I also verified the behavior.
```bash
-> % node
Welcome to Node.js v22.11.0.
Type ".help" for more information.
> const m = require('module');
undefined
> m.findSourceMap('/not/a/file');
undefined
```
I am looking for the best way to update Node typings to reflect the actual return type.
Related to https://github.com/opennextjs/opennextjs-cloudflare/issues/135

fix(module): return `undefined` with `findSourceMap`

---

src/runtime/node/http/internal/request.ts
src/runtime/node/http/internal/response.ts
src/runtime/node/net/internal/socket.ts
src/runtime/node/stream/internal/readable.ts
src/runtime/node/stream/internal/writable.ts
src/runtime/node/tls/internal/server.ts
src/runtime/node/tls/internal/tls-socket.ts
src/runtime/node/tty/internal/read-stream.ts

Change node:events import from relative to package import.
@pi0 There are a few relative imports for the net package. I left them untouched to stay on the safe side.
Let me know if it's the right thing to do - if it is, I'd like to add comment there too.
Thanks 🙏
Context: https://github.com/unjs/unenv/issues/353#issuecomment-2508064030

refactor: use `node:events` instead of relative path 

---

src/runtime/node/module/$cloudflare.ts

This was trigering the following error:
```
-> % npx wrangler dev
⛅️ wrangler 3.91.0
-------------------
✘ [ERROR] Build failed with 1 error:
✘ [ERROR] Could not resolve "src/runtime/_internal/utils"
node_modules/.pnpm/unenv@file+..+unenv/node_modules/unenv/runtime/node/module/$cloudflare.mjs:53:31:
53 │ import { notImplemented } from "src/runtime/_internal/utils";
╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
You can mark the path "src/runtime/_internal/utils" as external to exclude it from the bundle,
which will remove this error.
```
edits: 
- the cumprit is this [PR](https://github.com/unjs/unenv/pull/351) last week by me
- I create https://github.com/unjs/unenv/issues/357 to try to solve this at build time

fix(cloudflare): import notImplemented using a relative path

---

eslint.config.mjs

fixes #357
```
-> % pnpm lint
> unenv@1.9.0 lint /Users/vberchet/code/work/unenv
> eslint . && prettier -c src test
/Users/vberchet/code/work/unenv/src/runtime/node/fs/index.ts
16:1  error  'src/runtime/_internal/utils' import is restricted from being used by a pattern. Use relative imports instead  no-restricted-imports
✖ 1 problem (1 error, 0 warnings)
 ELIFECYCLE  Command failed with exit code 1.
 ```

chore: disallow `src/` imports with eslint

---

test/workerd/tests.mjs

Ref: Added as part of #353 discussions. /cc @vicb
This PR adds a test for h3 fetch util used today in Nitro v1 and h3 for various purposes.

test: add workerd test for unenv/fetch

---

src/presets/cloudflare.ts
src/runtime/node/http/internal/request.ts
src/runtime/node/http/internal/response.ts
test/workerd/tests.mjs
tsconfig.json

(ref: https://github.com/unjs/unenv/pull/352, https://github.com/unjs/unenv/issues/353, https://github.com/unjs/unenv/issues/355)
This allow hybrid polyfills to rewrite the import path.
i.e to import from "node:streaml".
fixes https://github.com/unjs/unenv/issues/353
introduces https://github.com/unjs/unenv/issues/364

refactor(http, cloudflare): use `unenv/` imports inside `node:http`

---

src/runtime/node/process/internal/process.ts

`process.domain` was implemented as `mock.__createMock__("process.domain");`
Which means that 
1. `process.domain.bind(fn)` returned function will not call `fn`
2. `process.domain.run(fn, ...args)` will not execute `fn`
After the cloudflare hybrid polyfill [made use of `process.domain`](https://github.com/unjs/unenv/pull/335) we started [seeing issue](https://github.com/cloudflare/workers-sdk/issues/7072) with the `pg` npm packages.
Those issues are triggered by [code similar to](https://github.com/search?q=repo%3Abrianc%2Fnode-postgres%20%22.domain%22&type=code): 
```ts
if (process.domain && config.callback) {
this.callback = process.domain.bind(config.callback)
}
```
In this snippet, the callback (`config.callback`) will never be executed.
We considered implementing bind as `(fn) => fn` …

refactor(node:process): set `process.domain` to `undefined`

---

src/presets/nodeless.ts
test/workerd/tests.mjs

[As per `exports` definition in package.json](https://github.com/unjs/unenv/blob/main/package.json#L16-L19), some modules don’t have fully qualified specifier so using them throws `ERR_MODULE_NOT_FOUND` error.
Two other things to note:
1. Is there a reason why we don’t use unev version of Buffer? Currently it’s expected `buffer` package is installed but I thinks was not intended?
2. I’ve tried running tests for Workerd but I’m getting following error:
<details>
<summary>Error output</summary>
```
Workerd: 1.20241202.0 (compatibility date: 2024-12-02)
Module fallback server listening on http://localhost:8888
Running tests...
workerd/server/server.c++:4025: debug: [ TEST ] tests:crypto_getRandomValues
workerd/server/server.c++:3052: error: Fallback service failed to fetch module; payload = …
```

fix(nodelss): use valid esm inject paths

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml
src/env.ts
src/types.ts
test/env.test.ts

This PR adds a new `defineEnv({ presets: [], ... }): { env }` utility aiming to replace `env(presets[]): env` util for integration usage.
The benefit of this one is that it can be extendable with more features, options and shortcuts.
Example:
```ts
const { env } = defineEnv({
nodeCompat: true,
presets: [myPreset],
overrides: {}
});
```

feat: `defineEnv` util

---

src/env.ts
src/presets/cloudflare.ts
src/presets/node.ts
src/presets/nodeless.ts
src/types.ts
tsconfig.json

This PR adds `meta` to the presets which is useful for external presets meta. 
Presets are exposed from `defineEnv` for inspection and `path` is useful for #373

feat: presets meta

---

package.json
pnpm-lock.yaml
src/presets/cloudflare.ts
test/workerd/tests.mjs

Implemented in https://github.com/cloudflare/workerd/releases/tag/v1.20241213.0
/cc @anonrig

feat(cloudflare): use workerd implementation of node:dns

---

src/env.ts

This PR is a hotfix for `defineEnv` utility when it is running in an aliased `unenv-nightly` package and when package manager (pnpm) does **not** rename `"name"` field in `package.json`, it causes ESM resolution to fail.
Workaroud is to fallback to `unenv/` => `unenv-nightly/` and then id as-is.

fix(defineEnv): fallback support for `unenv-nightly`

---

src/env.ts

minor refactor to remove a cast (`string[]` is actually `Array<string | URL>`)

refactor: remove cast

---

src/runtime/node/timers/index.ts
test/workerd/tests.mjs

Co-authored-by: Yagiz Nizipli <yagiz@cloudflare.com>
Found while debugging mysql2 on workers
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #385 
- <kbd>&nbsp;1&nbsp;</kbd> #384 👈

fix(timers): bind global functions

---

src/runtime/node/timers/$cloudflare.ts
src/runtime/node/timers/index.ts
test/workerd/tests.mjs

While `active` is deprecated, it used by popular libs.
[mysql](https://github.com/mysqljs/mysql/blob/dc9c152a87ec51a1f647447268917243d2eab1fd/lib/protocol/Timer.js#L14)
```js
Timer.prototype.active = function active() {
if (this._timeout) {
if (this._timeout.refresh) {
this._timeout.refresh();
} else {
Timers.active(this._timeout);
}
}
};
```
ref: [NodeJS implementation](https://github.com/nodejs/node/blob/0e7ec5e7a1427eb418bf82833a5c308cb8e0ecda/lib/timers.js#L354)
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #385 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #384

feat(timers): implement `active` and `_unrefActive` exports

---

src/runtime/node/tty/internal/read-stream.ts

The `WriteStream` already depends on `node:net`, I think this should be ok here?

refactor(tty): ReadStream depend on node:net

---

src/runtime/polyfill/deno-env.ts

Since Deno 2 the `process` variable is available globally.
Fixes https://github.com/unjs/unenv/issues/394

chore: remove old deno process polyfill

---

src/presets/cloudflare.ts
test/workerd/tests.mjs

Adds node:net and node:timers since they're both fully implemented in workers right now.

feat(cloudflare): add `node:net` and `node:timers`

---

README.md
src/env.ts
src/index.ts
src/presets/index.ts

This PR drops legacy merging until `env` in favor of the new `defineEnv` util (#372)
Also drops internals `mapArrToVal` and `NodeBuiltinModules`

refactor!: remove legacy presets in favor of `defineEnv`

---

src/runtime/node/buffer.ts
src/runtime/node/child_process.ts
src/runtime/node/constants.ts
src/runtime/node/dgram.ts
src/runtime/node/diagnostics_channel.ts
src/runtime/node/dns.ts
src/runtime/node/dns/promises.ts
src/runtime/node/domain.ts
src/runtime/node/fs.ts
src/runtime/node/fs/promises.ts
src/runtime/node/http.ts
src/runtime/node/http2.ts
src/runtime/node/https.ts
src/runtime/node/inspector.ts
src/runtime/node/internal/fs/promises.ts
src/runtime/node/os.ts
src/runtime/node/readline.ts
src/runtime/node/readline/promises.ts
src/runtime/node/stream.ts
src/runtime/node/stream/consumers.ts
src/runtime/node/stream/promises.ts
src/runtime/node/stream/web.ts
src/runtime/node/string_decoder.ts
src/runtime/node/tls.ts
src/runtime/node/trace_events.ts
src/runtime/node/tty.ts
src/runtime/node/util.ts
src/runtime/node/v8.ts
src/runtime/node/vm.ts
src/runtime/node/worker_threads.ts

Use `{} satisfies T` when possible for better emitted types and safety and also `{} as T` instead of `<T>{}` for node stript type compatibility (marked as TODO to migrate to satisfies)

refactor: use `satisfies T` when possible

---

README.md
src/runtime/node/assert.ts
src/runtime/node/assert/strict.ts
src/runtime/node/repl.ts
src/runtime/node/stream.ts
src/runtime/node/zlib.ts

Full coverage of Node.js (v22.13.0) exports

fix: full coverage for (esm) node exports

---

src/runtime/node/assert.ts
src/runtime/node/async_hooks.ts
src/runtime/node/buffer.ts
src/runtime/node/child_process.ts
src/runtime/node/console.ts
src/runtime/node/constants.ts
src/runtime/node/dgram.ts
src/runtime/node/diagnostics_channel.ts
src/runtime/node/dns.ts
src/runtime/node/domain.ts
src/runtime/node/http.ts
src/runtime/node/http2.ts
src/runtime/node/inspector.ts
src/runtime/node/net.ts
src/runtime/node/os.ts
src/runtime/node/perf_hooks.ts
src/runtime/node/punycode.ts
src/runtime/node/readline.ts
src/runtime/node/stream.ts
src/runtime/node/string_decoder.ts
src/runtime/node/timers.ts
src/runtime/node/tls.ts
src/runtime/node/trace_events.ts
src/runtime/node/tty.ts
src/runtime/node/util.ts
src/runtime/node/v8.ts
src/runtime/node/vm.ts
src/runtime/node/wasi.ts
src/runtime/node/worker_threads.ts
src/runtime/node/zlib.ts

minor change.
`assert` was node importing the type only.
Took the opportunity to unify all node type imports

refactor: import node types as nodeSomeModule

---

src/presets/nodeless.ts

The modules were added in #424

refactor: add `node:repl` and `node:inspector/promises` to the nodeless preset

---

src/runtime/node/cluster.ts
src/runtime/node/console.ts
src/runtime/node/dns.ts
src/runtime/node/dns/promises.ts
src/runtime/node/http.ts
src/runtime/node/http2.ts
src/runtime/node/https.ts
src/runtime/node/inspector.ts
src/runtime/node/inspector/promises.ts
src/runtime/node/internal/fs/classes.ts
src/runtime/node/internal/http/agent.ts
src/runtime/node/stream.ts
src/runtime/web/performance/_performance.ts

Proxy-based mocks are dangerous and can cause implicit behaviors in libraries.
Since we have migrated almost everything to explicit APIs for v2, this PR updates a few last places to use `notImplementedClass`. (this can cause some breaking changes however this way we can catch those usages and explicitly implement the desired behavior).
As part of migration implemented `http.Agent` polyfill (to polyfill `globalAgent` exports)
/cc @anonrig @vicb

refactor!: avoid proxy mock usage

---

package.json
pnpm-lock.yaml
src/runtime/mock/proxy.ts
test/mock.test.ts

resolves #212
implement `.then` / `.catch` / `.finally` support for mock proxy + add tests and minor fixes.
Note: As of #438, unenv does not internally depend on this proxy anymore

fix(mock/proxy): support promises 

---

src/runtime/node/util.ts

This will avoid importing code when `node:util/types` is implemented by a preset

fix(util): import `types` from `node:util/types`

---

src/runtime/polyfill/process.ts

Use `node:process` for `unenv/polyfill/process` (used by nitro v2). This allows properly pulling-in hybrid polyfills (or natives) for example with cloudflare.

fix: use `node:process` for polyfill

---

src/runtime/node/internal/process/hrtime.ts
src/runtime/node/internal/process/nexttick.ts
src/runtime/node/process.ts

This is needed so that cloudflare (i.e. any runtime with a `nextTick` impl) can drop the polyfill

refactor(process)!: extract nextTick to a separate file

---

src/runtime/node/internal/util/inherits.ts
src/runtime/node/internal/util/promisify.ts
src/runtime/node/util.ts
src/runtime/npm/inherits.ts

fixes related to #449
- general code readability 
- inherits is tree-shakable ([repl](https://esbuild.github.io/try/#YgAwLjI1LjAALS1idW5kbGUAZQBlbnRyeS50cwBpbXBvcnQgdHlwZSB1dGlsIGZyb20gIm5vZGU6dXRpbCI7Cgpjb25zdCBjdXN0b21TeW1ib2wgPSAvKkBfX1BVUkVfXyovIFN5bWJvbCgiY3VzdG9tUHJvbWlzaWZ5Iik7Cgp0eXBlIEZuID0gKC4uLmFyZ3M6IGFueVtdKSA9PiBhbnk7CgpmdW5jdGlvbiBfcHJvbWlzaWZ5KGZuOiBGbiAmIHsgW2N1c3RvbVN5bWJvbF0/OiBGbiB9KSB7CiAgaWYgKGZuW2N1c3RvbVN5bWJvbF0pIHsKICAgIHJldHVybiBmbltjdXN0b21TeW1ib2xdOwogIH0KICByZXR1cm4gZnVuY3Rpb24gKC4uLmFyZ3M6IGFueVtdKSB7CiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4gewogICAgICB0cnkgewogICAgICAgIC8vIEB0cy1pZ25vcmUKICAgICAgICBmbi5jYWxsKHRoaXMsIC4uLmFyZ3MsIChlcnIsIHZhbCkgPT4gewogICAgICAgICAgaWYgKGVycikgewogICAgICAgICAgICByZXR1cm4gcmVqZWN0KGVycik7CiAgICAgICAgICB9CiAgICA …

refactor: improve `node:util` tree-shaking

---

src/runtime/node/util.ts

should fix #449
Even if not using `default` export of `unenv/node/util`, esbuild was pulling all utils in (see #382 for issue)
This PR uses explicit import/exports to avoid this.
Manual test:
```bash
pnpm build && echo "export { parseArgs } from 'unenv/node/util';" | pnpm esbuild --bundle --platform=node --format=esm --tree-shaking=true --outfile=dist/_test.mjs
```

fix: fix tree-shaking issues with `node/util`

---

src/runtime/node/internal/perf_hooks/performance.ts
src/runtime/polyfill/performance.ts
src/runtime/web/performance/_performance.ts

@pi0 That should be enough for us to fix our "performance issue".
It would be nice to remove the circular dep `Performance` -> `perfomance` (`Perfomance#now` & `performance = new Performance`) but it is not a problem for us at this point.
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #463 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #461

fix: circular dependency between node and web `performance.now()`

---

src/preset.ts
test/env.test.ts

This PR improves node compat injects preset:
- Use `node:buffer` for `Buffer` inject (this way native aliases are considered) 
- Add `setImmediate` and `clearImmediate` from `node:timers`
Note: Test updated as currently `resolve: true` does not respects aliases fixing in next one!
/cc @vicb

feat: update node compat injects

---

src/env.ts
test/env.test.ts

It is possible to disable alias and injects by overriding their values with `false`
However it is is not possible to disable items from `polyfil` and `external` arrays.
This PR allows using `!<id>` to disable them via preset overrides.

feat(defineEnv): support disabling `polyfill` and `external` with `!` prefix

---

src/runtime/node/inspector/promises.ts
src/runtime/node/readline.ts
src/runtime/node/stream.ts
src/runtime/node/timers.ts

Leftover follow-up from #460
This PR changes `promises` export from `node:<id>` modules to use `node:<id>/promises` default export instead of using local paths which increases ability to implement hybrid by only implementing `/promises` variant.
Updated `inspector/promises.ts` to remove circular dep issue.
/cc @vicb can you please check specially for `node:timers/promises` if won't make any potential trouble for you?

refactor: prefer `node:*/promises` for `promises` export

---

src/runtime/node/http2.ts
src/runtime/node/internal/async_hooks/async-hook.ts
src/runtime/node/internal/events/events.ts
src/runtime/node/vm.ts
src/runtime/node/worker_threads.ts

Some leftover symbols not marked as pure (which cases esbuild to not treeshake any usage of them)

refactor: mark all symbol inits as pure to allow treeshake

---

src/runtime/node/internal/process/env.ts
test/node-env.test.ts

Logging `process.env` polyfill was always leading to `{}` (while `process.env.TEST` worked) this PR makes debugging and `Object.keys`/`Object.entries` work.
This PR also fixes order to respect `globalThis.__env__` if set

fix(process): add `getOwnPropertyDescriptor` for `process.env`

---

src/runtime/web/performance/_polyfills.ts

discovered from #478
This PR makes consistent insternal polyfill for performance.now (either native or ms after origin) + safer access to performance.now (with conditional checks)

fix(web/performance): use consistent performance.now checks

---

src/runtime/node/internal/perf_hooks/performance.ts
src/runtime/node/perf_hooks.ts
src/runtime/web/performance/_polyfills.ts
src/runtime/web/performance/index.ts

Followup #478
workerd runtime, provides `globalThis.performance` but only `timeOrigin: 0` + `now()` (which we anyway always pick and use also in polyfill.
/cc @vicb wondering after this two PRs, do we even need a hybrid entry on cloudflare preset?

fix: validate `globalThis.performance` before reexporting it

---

src/runtime/node/events.ts
src/runtime/node/internal/events/events.ts

Top level exports unenv has for `node:events` are mainly for coverage purposes. Some, like `node:events.listenerCount` fail on Node.js itself.
```
> events.listenerCount()
Uncaught TypeError: Cannot read properties of undefined (reading 'listenerCount')
at Function.listenerCount (node:events:835:22)
```
This PR makes side-effect free and remove dependency loops.

refactor(node:events): simple top level exports

---

src/runtime/node/internal/process/process.ts

https://github.com/nuxt/nuxt/issues/31290
`process.getBuiltinModule` in Node.js returns undefined for unsupported modules. 
This PR makes mock backward compatible with unenv v1.

fix(node:process): return undefined for `getBuiltinModule`

---

src/runtime/node/internal/tty/read-stream.ts
src/runtime/node/internal/tty/write-stream.ts
src/runtime/node/tty.ts

(context: found while investigating https://github.com/nuxt-hub/core/issues/499)
Current `ReadStream`/`WriteStream` polyfill implementations used for `process.std{in,out,err}` polyfills are extending `node:net` wrongly.
This causes not only extra bundle impact when not used (in pure polyfill mode) but also is the wrong extension as `tty` is not a network socket and also internal cycling dependencies.
Also `process.std{out,err}.write` was completely nonfunctional.
I have implemented both as partial types with `WriteStream.write` redirect to real `console` as polyfill.
I don't expect any libraries in compat mode to expect more tty methods but we can later explicitly implement/mock them if needed. Alternatively, overlay presets can check implementation.

refactor(node:tty): standalone implementations

---

src/runtime/node/internal/events/events.ts

(context: found while investigating https://github.com/nuxt-hub/core/issues/499 / followup of #488)
Currently `Process` polyfill extends `EventEmitter` but internal implementation of `EventEmitter` also uses process methods which makes a circular dependency.
This PR fixes issue by replacing simple usages in `EventEmitter`

fix: avoid circular dependency between `process` and `node:events`

---

src/runtime/node/tty.ts

Fixes: https://github.com/unjs/unenv/issues/512

fix(node): tty default export for `ReadStream`
